esphome:
  name: wattmeter
  friendly_name: WattMeter
  platformio_options:
    upload_speed: 115200 # Example upload speed

esp32:
  # platform: ESP32
  board: m5stack-atom
  framework:
    type: arduino

# Enable logging
logger:
  #level: INFO
  logs:
    light: NONE

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_password

web_server:
  port: 80
  id: webota
  auth:
    username: !secret web_server_username
    password: !secret web_server_password

wifi:
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "intelliflo"
    password: !secret intelliflo_hotspot_password

captive_portal:

time:
  - platform: homeassistant
    id: homeassistant_time
#text_sensor:
#  - platform: pentair_intelliflo
#    program:
#      name: "Program"

button:
  # - platform: template
  #   name: "Pentair test"
  #   entity_category: CONFIG
  #   on_press: 
  #     then: 
  #       - lambda: !lambda |- 
  #           id(pentair).pumpToRemoteControl();
  #           id(pentair).commandRPM(1000);
  - platform: restart
    name: "Atom_Restart"
    id: atomrestart

i2c:
  id: bus_a
  sda: GPIO25
  scl: GPIO21
  scan: True

ads1115:
  i2c_id: bus_a
  address: 0x48
#  continuous_mode: on
  id: ads1115_48
  


sensor:
# ads1115-48
  - name: "ADS1115 48 Channel A0-GND"
    id: ads1115_a0
    ads1115_id: ads1115_48
    multiplexer: 'A0_GND'
    gain: 6.144
    platform: ads1115
  - name: "ADS1115 48 Channel A1-GND"
    id: ads1115_a1
    ads1115_id: ads1115_48
    multiplexer: 'A1_GND'
    gain: 6.144
    platform: ads1115
  - name: "ADS1115 48 Channel A2-GND"
    id: ads1115_a2
    ads1115_id: ads1115_48
    multiplexer: 'A2_GND'
    gain: 6.144
    platform: ads1115
  - name: "ADS1115 48 Channel A3-GND"
    id: ads1115_a3
    ads1115_id: ads1115_48
    multiplexer: 'A3_GND'
    gain: 6.144
    platform: ads1115    

light:
  - platform: neopixelbus
    type: GRB
    pin: GPIO27
    num_leds: 1
    variant: sk6812
    name: "Atom RGB Light"
    id: atom_light
    restore_mode: RESTORE_DEFAULT_OFF
    effects:
      - random:
          name: "Random"
          transition_length: 1s
          update_interval: 1s
      - lambda:
          name: "Breathing Effect"
          update_interval: 150ms # Controls the smoothness of the fade
          lambda: |-
            static int step = 0;
            const int step_limit = 20; 
            float brightness;

            // Calculate a sine wave to create a smooth brightness change
            brightness = (sin(step * M_PI / step_limit) +1) *.40 + .1;

            // Set the color and brightness
            auto call = id(atom_light).turn_on();
            call.set_rgb(0.0, 1.0, 0.0); 
            call.set_transition_length(150);
            call.set_brightness(brightness);
            call.set_publish(false);
            call.set_save(false);
            call.perform();            
            step = ++step % (step_limit * 2);